osx_image: xcode7.1
language: objective-c

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace SpeedLog.xcworkspace -scheme SpeedLog -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
